### ISSUE TITLE
Need for RelayBandwidthRate and RelayBandwidthBurst?

### ISSUE THREAD

**Issue by sreknob** [Ilshidur/tor-relay-docker#11]
Hi - thanks so much for the update to the latest tor version! It's working nicely.

I was wondering, is there a reason that the container ENV defaults to 
```
ENV TOR_RelayBandwidthRate "100 KBytes"
ENV TOR_RelayBandwidthBurst "200 KBytes"
```
rather than only specifying them in the run command?
Tor's defaults, AFAIK is 0 for both of these.
I'm aware that I can set them to 0 as a variable, just curious :-)

**Comment by Ilshidur** [comment]
Hello sreknob.

I guess the reason why I did this back then was to make this image easily runnable for test purposes, so it would not need all those environment variables to run in an effective and non-invasive way. This way, the user running a container from this image just of the sake of trying it out won't risk having all their bandwidth being eaten up in case they forget it. ¯\_(ツ)_/¯
Now that I'm thinking about it, I realize this is a quite low limitation, even for testing.
