### ISSUE TITLE
DirPort not visible from Relay Search 

### ISSUE THREAD

**Issue by rdipalmadac** [Ilshidur/tor-relay-docker#17]
HI. I have successfully run your dock in Relay mode. But port 9030 is not seen.
This is my run script:
`docker run -d \
  --name tor-relay \
  -e RELAY_TYPE=relay \
  -e TOR_ORPort=9001 \
  -e TOR_DirPort=9030 \
  -e TOR_Nickname=NeapolitanTorRelay \
  -e TOR_ContactInfo="rosario.moggia@gmail.com" \
  -e TOR_RelayBandwidthRate="100 KBytes" \
  -e TOR_RelayBandwidthBurst="200 KBytes" \
  -e TZ=Europe/Rome \
  -e PUID=$(id -u) \
  -e PGID=$(id -g) \
  -v $(pwd)/tor/data:/data:Z \
  -p 9001:9001 \
  -p 9030:9030 \
  --restart always \`
![immagine](https://user-images.githubusercontent.com/125769652/228830282-244e9a3c-ffe5-498b-81b1-592097661c83.png)

I can tell you that port 9030 is open on the router and correctly routed. What mistake have I made?
Thanks

**Comment by Likogann** [comment]
Relays running 0.4.6.1-alpha or later no longer advertise the dir port address or port

**Comment by rdipalmadac** [comment]
Ok. Thanks
