### ISSUE TITLE
Port 9030 It is also necessary

### ISSUE THREAD

**Issue by irraz** [Ilshidur/tor-relay-docker#3]
Hi,

I need add -p 9001:9001 -p 9030:9030 too
Not only 9001 

9001 Orport
9030 Dirport

**Comment by Ilshidur** [comment]
Right. [I edited the README file](https://github.com/Ilshidur/tor-relay-docker/commit/fbc59d091ee5442b8bc20fc6be9aeded593d02b1) so you can configure use the examples to expose a DirPort on your relay.

**Comment by irraz** [comment]
Great!
