### ISSUE TITLE
Upgrade to 0.4.7.7 for congestion control on exits

### ISSUE THREAD

**Issue by sreknob** [Ilshidur/tor-relay-docker#9]
Hello,
Notification has gone out form the torproject.org encouraging upgrade of tor to 0.4.7.7 to enable "congestion control" to improve network performance on exits.
Looks like alpine has the 0.4.7.7-r1 package released.
If able, can you update and push a new image?
Thanks!

**Comment by Ilshidur** [comment]
Hello. Thank you for your interest on this project.

The docker image [has been updated accordingly](https://github.com/Ilshidur/tor-relay-docker/commit/45394d5930381b382f7ce127d9639d682b51127d) and now ships with version `0.4.7.7-r1`.

You can pull one of the following tags that ship the same image :
* `ilshidur/tor-relay:2.1`
* `ilshidur/tor-relay:2.1-v0.4.7.7-r1`
* `ilshidur/tor-relay:2.1-ls3.15-v0.4.7.7-r1`

See https://hub.docker.com/r/ilshidur/tor-relay/tags for a full list of tags.
